name: Deploy Umami to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AKS_RESOURCE_GROUP: my-prod-apps-rg
  AKS_CLUSTER_NAME: my-prod-aks

jobs:
  deploy-umami-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install kubectl and kustomize
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}

      - name: Deploy Umami
        working-directory: k8s/overlays/prod
        run: |
          kustomize build . | kubectl apply -f -
